create table if not exists user (
  usr_id INT(11) NOT NULL AUTO_INCREMENT,
  Fname VARCHAR(100) DEFAULT NULL,
  Lname VARCHAR(100) DEFAULT NULL,
  Sex VARCHAR(100) DEFAULT NULL,
  UserUserName VARCHAR(100) DEFAULT NULL,
  Country VARCHAR(100) DEFAULT NULL,
  Description VARCHAR(100) DEFAULT NULL,
  Email VARCHAR(100) DEFAULT NULL,
  Phone int(10) DEFAULT NULL,
  Bday DATE DEFAULT NULL,
  PRIMARY KEY (usr_id)
);
create table if not exists guide(
  usr_id INT(11) NOT NULL AUTO_INCREMENT,
  Fname VARCHAR(100) DEFAULT NULL,
  Lname VARCHAR(100) DEFAULT NULL,
  Sex VARCHAR(100) DEFAULT NULL,
  GuideUserName VARCHAR(100) DEFAULT NULL,
  Country VARCHAR(100) DEFAULT NULL,
  Description VARCHAR(100) DEFAULT NULL,
  Email VARCHAR(100) DEFAULT NULL,
  Phone int(10) DEFAULT NULL,
  Bday DATE DEFAULT NULL,
  PRIMARY KEY (usr_id)
);
